### PR TITLE
Fix complete conflict in word and internal link

### LINKED ISSUE #30: Take care uppercase when input words
According discussion in https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/29.

For instance, we have 'banana' in dictionary, if I type this word in the beginning of a sentence, I will type "Ba", but it will not complete currently, 
image

I guess ignore uppercase will be better. If "Banana" is in candidate list will be perfect.

### PR DESCRIPTION
**Pull request by chenyukang**
close #30

### CODE REVIEW

File: src/ui/AutoCompleteSuggest.ts [hunk 1]
```diff
@@ -30,14 +30,14 @@ function suggestWords(words: Word[], query: string, max: number): Word[] {
...
-      if (x.value === query) {
+      if (x.value === query || x.value.length < query.length) {
         return { word: x, alias: false };
       }
 
       if (
         x.value.startsWith("[[")
           ? lowerStartsWithoutSpace(x.value.replace("[[", ""), query)
-          : x.value.startsWith(query)
+          : startsWithoutSpace(x.value, query)
```
Comment (tadashi-aikawa) [inline src/ui/AutoCompleteSuggest.ts:40]: This is my mistake 👍

File: src/ui/AutoCompleteSuggest.ts [hunk 2]
```diff
@@ -30,14 +30,14 @@ function suggestWords(words: Word[], query: string, max: number): Word[] {
   const queryStartWithUpper = capitalizeFirstLetter(query) === query;
   return Array.from(words)
     .map((x) => {
-      if (x.value === query) {
+      if (x.value === query || x.value.length < query.length) {
```
Comment (tadashi-aikawa) [inline src/ui/AutoCompleteSuggest.ts:33]: @chenyukang 
Does this relate to this issue?

It will improve performance. On the other hand, there will be some problems when aliases (Custom dictionary and internal link) are longer than value. So I want to solve it after releasing v3.0.0.

**Review by tadashi-aikawa — COMMENTED** [review]
Thank you for PR!

File: src/ui/AutoCompleteSuggest.ts (hunk 2 above)
Comment (chenyukang) [reply src/ui/AutoCompleteSuggest.ts:33]: > 

I rollback this change now.
